
services:
  database:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: danamat07
      MYSQL_DATABASE: fitnessapp
      MYSQL_USER: root
      MYSQL_PASSWORD: danamat07
    ports:
      - "3306:3306"
    expose:
      - '3306'
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
